apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-site-com-cert
spec:
  secretName: site-com-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-homolog
  dnsNames:
    - "site.com"